name: numberpicker
version: 0.1.3
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/NumberPicker

environment:
  sdk: ">=1.23.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true